[platformio]
default_envs = esp32doit-devkit-v1

[env:esp32doit-devkit-v1]
platform = espressif32@7.1.1
board = esp32doit-devkit-v1
framework = arduino
platform_packages = platformio/framework-arduinoespressif32@3.20017.241212+sha.dcc1105b
build_unflags = -std=gnu++11
build_flags = -std=gnu++17

[env:native]
platform = native@1.2.1
test_framework = unity
lib_deps = throwtheswitch/Unity@2.6.1
test_build_src = yes
build_src_filter = +<*.cpp>
build_flags = -Itest/support
extra_scripts = pre:scripts/native_toolchain.py
